export const BRANDS = [
  {
    id: 1,
    name: "Damas",
    logo: "/assets/Brands/DAMAS.png",
    width: "187px",
    height: "35px",
  },
  {
    id: 2,
    name: "Decathlon",
    logo: "/assets/Brands/decathlon.svg",
    width: "187px",
    height: "40px",
  },
  {
    id: 3,
    name: "Livpure",
    logo: "/assets/Brands/LIVPure.png",
    width: "187px",
    height: "40px",
  },
  {
    id: 4,
    name: "Uber",
    logo: "/assets/Brands/Uber_logo.png",
    width: "187px",
    height: "30px",
  },
  {
    id: 5,
    name: "Kroger",
    logo: "/assets/Brands/Kroger.png",
    width: "187px",
    height: "120px",
  },
  {
    id: 6,
    name: "Societe Generale",
    logo: "/assets/Brands/SocieteGenerale.png",
    width: "187px",
    height: "25px",
  },
  {
    id: 7,
    name: "UniPer",
    logo: "/assets/Brands/UniPer.png",
    width: "187px",
    height: "90px",
  },
  {
    id: 8,
    name: "WalMart",
    logo: "/assets/Brands/WallMart.jpeg",
    width: "187px",
    height: "30px",
  },
  {
    id: 9,
    name: "Volkswagen",
    logo: "/assets/Brands/VolksWagen2.png",
    width: "187px",
    height: "70px",
  },
  {
    id: 10,
    name: "ICICI Bank",
    logo: "/assets/Brands/IcicBank.png",
    width: "187px",
    height: "50px",
  },
  {
    id: 11,
    name: "Embassy Group",
    logo: "/assets/Brands/EmbasyGroup.png",
    width: "187px",
    height: "60px",
  },
  {
    id: 12,
    name: "Enel",
    logo: "/assets/Brands/Enel.png",
    width: "187px",
    height: "60px",
  },
  {
    id: 13,
    name: "Karnataka Bank",
    logo: "/assets/Brands/KBL.jpeg",
    width: "187px",
    height: "60px",
  },
  {
    id: 14,
    name: "Comcast",
    logo: "/assets/Brands/Comcast.png",
    width: "187px",
    height: "60px",
  },
  {
    id: 15,
    name: "BCI",
    logo: "/assets/Brands/BCI.png",
    width: "187px",
    height: "50px",
  },
];
