export const TESTIMONIALS = [
  {
    id: 1,
    rating: 5,
    text: "Baaz delivered beyond expectations. Their team truly understands product development and business needs. We launched faster and smarter with their help.",
    name: "Ravi Verma",
    title: "Digital Marketing Specialist",
    avatar: "/assets/RaviVerma.jpeg",
  },
  {
    id: 2,
    rating: 5,
    text: "Baaz transformed our early-stage idea into a polished, scalable fintech product. Their attention to detail and communication made all the difference.",
    name: "Daniel Thompson",
    title: "Product Designer",
    avatar: "/assets/DanielThompson.jpeg",
  },
  {
    id: 3,
    rating: 5,
    text: "Working with Baaz was a game-changer. They delivered a robust solution on time and within budget. Highly recommended!",
    name: "Sarah Johnson",
    title: "CEO, TechStart",
    avatar: "/assets/SarahJohnson.jpeg",
  },
  {
    id: 4,
    rating: 5,
    text: "Baaz didn't just build us a product, they built infrastructure that converts non-customers into account holders at a rate our internal teams hadn't hit before. The speed and discipline of their delivery matched what we'd expect from a team three times the size.",
    name: "Siddharth Menon",
    title: "Vice President, ICICI Bank",
  },
  {
    id: 5,
    rating: 5,
    text: "We've worked with several product studios. Baaz is the first one that treated personalisation as a growth lever, not a feature checkbox. Our repurchase numbers tell the rest of the story.",
    name: "Jeff Bairn",
    title: "Head of AI Transformation, Harrys",
  },
  {
    id: 6,
    rating: 5,
    text: "Policy compliance was a manual nightmare before Baaz stepped in. Now our travel managers spend their time on strategy, not chasing approvals.",
    name: "Francisco Lozao",
    title: "President, Amadeus - Travel / Corporate",
  },
  {
    id: 7,
    rating: 5,
    text: "Baaz understood that our store associates are as much a sales channel as our website. They built for both and our online GMV grew because of it.",
    name: "Charlie Johnson",
    title: "Sales Director, Pip & Nut - Retail / Fashion",
  },
  {
    id: 8,
    rating: 5,
    text: "Tenant experience is the metric that matters most in our business, and it's the one Baaz moved the most. That's rare from an external engineering partner.",
    name: "Paul Ferraro",
    title: "Head of Sales, Hines - Real Estate / PropTech",
  },
];
